name: Release Pipeline

on:
  release:
    types: [created]

jobs:
  release:
    name: Release Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: mondoowebapp
      - name: Set up Go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: ${{ vars.GOVERSION }}
      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v1
        with:
          files: mondoowebapp
          token: ${{ secrets.GITHUB_TOKEN }}