name: Update Container

on:
  workflow_dispatch:
  push:
  repository_dispatch:
    types: [new_release]

permissions:
  packages: write

jobs:
  test:
    name: Container build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: Downloading latest release
      run: |
        wget https://github.com/atee86/mondoowebapp/releases/latest/download/mondoowebapp-all.zip
        unzip mondoowebapp-all.zip
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./bin
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/mondoowebapp-amd64-linux:latest
        file: mondoowebapp-amd64-linux
