name: Containerize Release

on:
  push:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  trigger-containerize:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Container Build
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d '{"event_type": "new_release"}' \
        https://api.github.com/repos/atee86/mondoocontainer/dispatches
