name: CNSPEC Test

on:
  push:

jobs:
  test:
    name: "Testing with CNSPEC"
    runs-on: ubuntu-latest

    steps:
    - name: Wait for installation
      run: |
        bash -c "$(curl -sSL https://install.mondoo.com/sh)"
    - name: Trigger Scan
      run: |
        cnspec scan local
