name: Test Workflow

on:
  workflow_dispatch:
  push:

permissions:
  actions: write
  contents: write

jobs:
  release:
    name: Release Binary
    runs-on: ubuntu-latest
    env:
      run_id: "12753212372"
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: mondoowebapp
          run-id: ${{ env.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: List files
        run: |
          ls -al 
      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/mondoowebapp*
          tag_name: "v1.0.0"
