name: Test Workflow

on:
  workflow_dispatch:
  push:

permissions:
  actions: write

jobs:
  testworkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Test Workflow
        id: test
        run: |
          response=$(curl -X POST -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
              -d '{"ref": "main"}')
          echo $response
          run_id=$(curl -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/runs \
              | jq -r '.workflow_runs[] | select(.head_branch=="main") | .id' \
              | head -n 1)
          echo "run_id=$run_id" >> $GITHUB_ENV
          echo "The run id is: $run_id"
